pipeline {
    agent any

    environment {
        IMAGE_NAME = "gitea.mjdev.dev/gitadmin/registery/devjams-web"
        IMAGE_TAG = "${env.BUILD_ID}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Web') {
            when {
                anyOf {
                    changeset "apps/web/**"
                    changeset "packages/api/**"
                }
            }
            steps {
                echo "Web-related changes detected. Building..."

                withCredentials([usernamePassword(
                    credentialsId: 'gitea_cred',
                    passwordVariable: 'GITEA_TOKEN',
                    usernameVariable: 'GITEA_USERNAME'
                )]) {
                    sh """
                        echo ${GITEA_TOKEN} | docker login gitea.mjdev.dev -u ${GITEA_USERNAME} --password-stdin
                        docker build -f apps/web/Dockerfile.web -t ${IMAGE_NAME}:${IMAGE_TAG} .
                        docker push ${IMAGE_NAME}:${IMAGE_TAG}
                    """
                }
            }
        }

        stage('Update Web Tag') {
            when {
                anyOf {
                    changeset "apps/web/**"
                    changeset "packages/api/**"
                }
            }
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'ghcr_cred',
                    passwordVariable: 'GITHUB_PASSWORD',
                    usernameVariable: 'GITHUB_USERNAME'
                )]) {

                    git branch: 'main',
                        credentialsId: 'ghcr_cred',
                        url: 'https://github.com/majeed4u/devjams-k8s.git'

                    sh '''
                        git config --global user.email "jamodah20@gmail.com"
                        git config --global user.name "majeed4u"

                        sed -i 's|^  tag:.*|  tag: "'"${IMAGE_TAG}"'"|' web/values.yaml

                        git add web/values.yaml
                        git commit -m "Updated web tag to '${IMAGE_TAG}' [ci skip]" || echo "No changes to commit"
                        git pull --rebase origin main || true
                        git push https://${GITHUB_USERNAME}:${GITHUB_PASSWORD}@github.com/majeed4u/devjams-k8s.git
                    '''
                }
            }
        }
    }
}