

pipeline {
    agent any

    environment {
        IMAGE_NAME = "gitea.mjdev.dev/gitadmin/registery/devjams-server"
        IMAGE_TAG = "${env.BUILD_ID}"
    }

    stages {
        stage('Pull from Git') {
            steps {
                git branch: 'main', credentialsId: 'github_pat_cred', url: 'https://github.com/majeed4u/devsjam.git'
            }
        }

        stage('Login and build image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'gitea_cred', passwordVariable: 'GITEA_TOKEN', usernameVariable: 'GITEA_USERNAME')]) {
                    sh """
                    # Login to Gitea
                    echo ${GITEA_TOKEN} | docker login gitea.mjdev.dev -u ${GITEA_USERNAME} --password-stdin
                    
                    docker build -f apps/server/Dockerfile.server -t ${IMAGE_NAME}:${IMAGE_TAG} .
                    docker push ${IMAGE_NAME}:${IMAGE_TAG}
                    """
                }
            }
        }

        stage('Update Tag') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github_pat_cred', passwordVariable: 'GITHUB_PASSWORD', usernameVariable: 'GITHUB_USERNAME')]) {
                    git branch: 'main', credentialsId: 'github_pat_cred', url: 'https://github.com/majeed4u/devsjam.git'

                    sh """
                    # Update the tag in the YAML file
                    sed -i 's/tag: [0-9]\\+/tag: ${IMAGE_TAG}/' k8s/server/values.yaml

                    # Force add and commit if there are changes
                    git add k8s/server/values.yaml
                    git commit -m "Updated login tag to ${IMAGE_TAG}" || echo "No changes to commit"

                    # Ensure git can authenticate using the stored credentials
                    git config --global credential.helper 'store'
                    echo "machine github.com login ${GITHUB_USERNAME} password ${GITHUB_PASSWORD}" > ~/.netrc
                    chmod 600 ~/.netrc

                    # Push the changes
                    git push https://github.com/majeed4u/devsjam.git
                    """
                }
            }
        }

        
    }
}
