/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ArchiveIndexRouteImport } from './routes/archive/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BlogSlugIndexRouteImport } from './routes/blog/$slug/index'
import { Route as AdminPostIndexRouteImport } from './routes/admin/post/index'
import { Route as AdminNewsletterIndexRouteImport } from './routes/admin/newsletter/index'
import { Route as AdminCommentsIndexRouteImport } from './routes/admin/comments/index'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin/analytics/index'
import { Route as BlogTagTagIndexRouteImport } from './routes/blog/tag/$tag/index'
import { Route as BlogSeriesSeriesIndexRouteImport } from './routes/blog/series/$series/index'
import { Route as BlogCategoryCategoryIndexRouteImport } from './routes/blog/category/$category/index'
import { Route as AdminPostPublishedIndexRouteImport } from './routes/admin/post/published/index'
import { Route as AdminPostNewIndexRouteImport } from './routes/admin/post/new/index'
import { Route as AdminPostArchivedIndexRouteImport } from './routes/admin/post/archived/index'
import { Route as AdminPostPostIdEditIndexRouteImport } from './routes/admin/post/$postId/edit/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIndexRoute = ArchiveIndexRouteImport.update({
  id: '/archive/',
  path: '/archive/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BlogSlugIndexRoute = BlogSlugIndexRouteImport.update({
  id: '/blog/$slug/',
  path: '/blog/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostIndexRoute = AdminPostIndexRouteImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNewsletterIndexRoute = AdminNewsletterIndexRouteImport.update({
  id: '/newsletter/',
  path: '/newsletter/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommentsIndexRoute = AdminCommentsIndexRouteImport.update({
  id: '/comments/',
  path: '/comments/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BlogTagTagIndexRoute = BlogTagTagIndexRouteImport.update({
  id: '/blog/tag/$tag/',
  path: '/blog/tag/$tag/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSeriesSeriesIndexRoute = BlogSeriesSeriesIndexRouteImport.update({
  id: '/blog/series/$series/',
  path: '/blog/series/$series/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoryCategoryIndexRoute =
  BlogCategoryCategoryIndexRouteImport.update({
    id: '/blog/category/$category/',
    path: '/blog/category/$category/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPostPublishedIndexRoute = AdminPostPublishedIndexRouteImport.update({
  id: '/post/published/',
  path: '/post/published/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostNewIndexRoute = AdminPostNewIndexRouteImport.update({
  id: '/post/new/',
  path: '/post/new/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostArchivedIndexRoute = AdminPostArchivedIndexRouteImport.update({
  id: '/post/archived/',
  path: '/post/archived/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostPostIdEditIndexRoute =
  AdminPostPostIdEditIndexRouteImport.update({
    id: '/post/$postId/edit/',
    path: '/post/$postId/edit/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/archive/': typeof ArchiveIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/search/': typeof SearchIndexRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/comments/': typeof AdminCommentsIndexRoute
  '/admin/newsletter/': typeof AdminNewsletterIndexRoute
  '/admin/post/': typeof AdminPostIndexRoute
  '/blog/$slug/': typeof BlogSlugIndexRoute
  '/admin/post/archived/': typeof AdminPostArchivedIndexRoute
  '/admin/post/new/': typeof AdminPostNewIndexRoute
  '/admin/post/published/': typeof AdminPostPublishedIndexRoute
  '/blog/category/$category/': typeof BlogCategoryCategoryIndexRoute
  '/blog/series/$series/': typeof BlogSeriesSeriesIndexRoute
  '/blog/tag/$tag/': typeof BlogTagTagIndexRoute
  '/admin/post/$postId/edit/': typeof AdminPostPostIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/archive': typeof ArchiveIndexRoute
  '/blog': typeof BlogIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/search': typeof SearchIndexRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/comments': typeof AdminCommentsIndexRoute
  '/admin/newsletter': typeof AdminNewsletterIndexRoute
  '/admin/post': typeof AdminPostIndexRoute
  '/blog/$slug': typeof BlogSlugIndexRoute
  '/admin/post/archived': typeof AdminPostArchivedIndexRoute
  '/admin/post/new': typeof AdminPostNewIndexRoute
  '/admin/post/published': typeof AdminPostPublishedIndexRoute
  '/blog/category/$category': typeof BlogCategoryCategoryIndexRoute
  '/blog/series/$series': typeof BlogSeriesSeriesIndexRoute
  '/blog/tag/$tag': typeof BlogTagTagIndexRoute
  '/admin/post/$postId/edit': typeof AdminPostPostIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/archive/': typeof ArchiveIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/search/': typeof SearchIndexRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/comments/': typeof AdminCommentsIndexRoute
  '/admin/newsletter/': typeof AdminNewsletterIndexRoute
  '/admin/post/': typeof AdminPostIndexRoute
  '/blog/$slug/': typeof BlogSlugIndexRoute
  '/admin/post/archived/': typeof AdminPostArchivedIndexRoute
  '/admin/post/new/': typeof AdminPostNewIndexRoute
  '/admin/post/published/': typeof AdminPostPublishedIndexRoute
  '/blog/category/$category/': typeof BlogCategoryCategoryIndexRoute
  '/blog/series/$series/': typeof BlogSeriesSeriesIndexRoute
  '/blog/tag/$tag/': typeof BlogTagTagIndexRoute
  '/admin/post/$postId/edit/': typeof AdminPostPostIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/login'
    | '/admin/'
    | '/archive/'
    | '/blog/'
    | '/profile/'
    | '/search/'
    | '/admin/analytics/'
    | '/admin/comments/'
    | '/admin/newsletter/'
    | '/admin/post/'
    | '/blog/$slug/'
    | '/admin/post/archived/'
    | '/admin/post/new/'
    | '/admin/post/published/'
    | '/blog/category/$category/'
    | '/blog/series/$series/'
    | '/blog/tag/$tag/'
    | '/admin/post/$postId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/admin'
    | '/archive'
    | '/blog'
    | '/profile'
    | '/search'
    | '/admin/analytics'
    | '/admin/comments'
    | '/admin/newsletter'
    | '/admin/post'
    | '/blog/$slug'
    | '/admin/post/archived'
    | '/admin/post/new'
    | '/admin/post/published'
    | '/blog/category/$category'
    | '/blog/series/$series'
    | '/blog/tag/$tag'
    | '/admin/post/$postId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/login'
    | '/admin/'
    | '/archive/'
    | '/blog/'
    | '/profile/'
    | '/search/'
    | '/admin/analytics/'
    | '/admin/comments/'
    | '/admin/newsletter/'
    | '/admin/post/'
    | '/blog/$slug/'
    | '/admin/post/archived/'
    | '/admin/post/new/'
    | '/admin/post/published/'
    | '/blog/category/$category/'
    | '/blog/series/$series/'
    | '/blog/tag/$tag/'
    | '/admin/post/$postId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ArchiveIndexRoute: typeof ArchiveIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  BlogSlugIndexRoute: typeof BlogSlugIndexRoute
  BlogCategoryCategoryIndexRoute: typeof BlogCategoryCategoryIndexRoute
  BlogSeriesSeriesIndexRoute: typeof BlogSeriesSeriesIndexRoute
  BlogTagTagIndexRoute: typeof BlogTagTagIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/': {
      id: '/archive/'
      path: '/archive'
      fullPath: '/archive/'
      preLoaderRoute: typeof ArchiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/blog/$slug/': {
      id: '/blog/$slug/'
      path: '/blog/$slug'
      fullPath: '/blog/$slug/'
      preLoaderRoute: typeof BlogSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/post/': {
      id: '/admin/post/'
      path: '/post'
      fullPath: '/admin/post/'
      preLoaderRoute: typeof AdminPostIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/newsletter/': {
      id: '/admin/newsletter/'
      path: '/newsletter'
      fullPath: '/admin/newsletter/'
      preLoaderRoute: typeof AdminNewsletterIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comments/': {
      id: '/admin/comments/'
      path: '/comments'
      fullPath: '/admin/comments/'
      preLoaderRoute: typeof AdminCommentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/analytics'
      fullPath: '/admin/analytics/'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/blog/tag/$tag/': {
      id: '/blog/tag/$tag/'
      path: '/blog/tag/$tag'
      fullPath: '/blog/tag/$tag/'
      preLoaderRoute: typeof BlogTagTagIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/series/$series/': {
      id: '/blog/series/$series/'
      path: '/blog/series/$series'
      fullPath: '/blog/series/$series/'
      preLoaderRoute: typeof BlogSeriesSeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$category/': {
      id: '/blog/category/$category/'
      path: '/blog/category/$category'
      fullPath: '/blog/category/$category/'
      preLoaderRoute: typeof BlogCategoryCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/post/published/': {
      id: '/admin/post/published/'
      path: '/post/published'
      fullPath: '/admin/post/published/'
      preLoaderRoute: typeof AdminPostPublishedIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/post/new/': {
      id: '/admin/post/new/'
      path: '/post/new'
      fullPath: '/admin/post/new/'
      preLoaderRoute: typeof AdminPostNewIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/post/archived/': {
      id: '/admin/post/archived/'
      path: '/post/archived'
      fullPath: '/admin/post/archived/'
      preLoaderRoute: typeof AdminPostArchivedIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/post/$postId/edit/': {
      id: '/admin/post/$postId/edit/'
      path: '/post/$postId/edit'
      fullPath: '/admin/post/$postId/edit/'
      preLoaderRoute: typeof AdminPostPostIdEditIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
  AdminCommentsIndexRoute: typeof AdminCommentsIndexRoute
  AdminNewsletterIndexRoute: typeof AdminNewsletterIndexRoute
  AdminPostIndexRoute: typeof AdminPostIndexRoute
  AdminPostArchivedIndexRoute: typeof AdminPostArchivedIndexRoute
  AdminPostNewIndexRoute: typeof AdminPostNewIndexRoute
  AdminPostPublishedIndexRoute: typeof AdminPostPublishedIndexRoute
  AdminPostPostIdEditIndexRoute: typeof AdminPostPostIdEditIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
  AdminCommentsIndexRoute: AdminCommentsIndexRoute,
  AdminNewsletterIndexRoute: AdminNewsletterIndexRoute,
  AdminPostIndexRoute: AdminPostIndexRoute,
  AdminPostArchivedIndexRoute: AdminPostArchivedIndexRoute,
  AdminPostNewIndexRoute: AdminPostNewIndexRoute,
  AdminPostPublishedIndexRoute: AdminPostPublishedIndexRoute,
  AdminPostPostIdEditIndexRoute: AdminPostPostIdEditIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ArchiveIndexRoute: ArchiveIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  BlogSlugIndexRoute: BlogSlugIndexRoute,
  BlogCategoryCategoryIndexRoute: BlogCategoryCategoryIndexRoute,
  BlogSeriesSeriesIndexRoute: BlogSeriesSeriesIndexRoute,
  BlogTagTagIndexRoute: BlogTagTagIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
